### ISSUE TITLE
Duplicated Paragraphs in Section 1.3.1 -  Version 0.5.2

### ISSUE THREAD

**Issue by MiaZhangDubai** [Qitmeer/whitepaper#38]
Three paragraphs of whitepaper **Version 0.5.2** in **1.3.1** are duplicated by mistake under openness and Proof-of-work.

Brackets mistake in section **1.2.1** under **predefined special roles** for the explanation of  "**SPV**"

**Comment by forchain** [comment]
thanks for reporting, fixed in 0.5.3
